name: Deploy Angular SSR to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Build Angular SSR app
        run: npm run build:ssr

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Firebase Functions dependencies
        run: |
          cd functions
          npm ci

      - name: Build Firebase Functions (SSR)
        run: |
          cd functions
          npm run build

      - name: Deploy to Firebase Hosting and Functions
        run: firebase deploy --project church-website-template-basic --token ${{ secrets.FIREBASE_TOKEN }}
